export const APPS = {
  about: {
    id: 'about',
    title: 'About',
    description: 'Learn about PAI — the private, bootable AI workstation that fits in your pocket.',
    icon: '/icons/about.svg',
    default: { w: 640, h: 480 },
    single: true,
  },
  docs: {
    id: 'docs',
    title: 'Docs',
    description: 'Full documentation for PAI: setup, apps, security model, and hardware compatibility.',
    icon: '/icons/docs.svg',
    default: { w: 900, h: 640 },
  },
  flash: {
    id: 'flash',
    title: 'Flash',
    description: 'Write PAI to a USB drive and boot a private AI workstation in minutes — no installation required.',
    icon: '/icons/flash.svg',
    default: { w: 720, h: 560 },
    single: true,
  },
  terminal: {
    id: 'terminal',
    title: 'Terminal',
    description: 'Full-featured terminal emulator on PAI with zsh, tmux, and common developer tools pre-installed.',
    icon: '/icons/terminal.svg',
    default: { w: 800, h: 500 },
  },
  chat: {
    id: 'chat',
    title: 'Chat',
    description: 'Chat with local AI models on PAI — fully private, no internet connection, no cloud processing.',
    icon: '/icons/chat.svg',
    default: { w: 960, h: 640 },
  },
  security: {
    id: 'security',
    title: 'Security',
    description: 'PAI security model: airgap architecture, disk encryption, verified boot, and full threat model.',
    icon: '/icons/security.svg',
    default: { w: 900, h: 640 },
  },
  verify: {
    id: 'verify',
    title: 'Verify',
    description: 'Cryptographically verify your PAI image against signed checksums before flashing to USB.',
    icon: '/icons/verify.svg',
    default: { w: 720, h: 520 },
  },
  hardware: {
    id: 'hardware',
    title: 'Hardware',
    description: 'PAI hardware compatibility guide — supported USB drives, laptops, and recommended configurations.',
    icon: '/icons/hardware.svg',
    default: { w: 800, h: 600 },
  },
  press: {
    id: 'press',
    title: 'Press Kit',
    description: 'PAI press kit — logos, screenshots, product descriptions, and media contact information.',
    icon: '/icons/press.svg',
    default: { w: 800, h: 600 },
  },
  changelog: {
    id: 'changelog',
    title: 'Changelog',
    description: 'PAI release history and changelog — what\'s new, fixed, and improved in each version.',
    icon: '/icons/changelog.svg',
    default: { w: 720, h: 560 },
  },
  faq: {
    id: 'faq',
    title: 'FAQ',
    description: 'Frequently asked questions about PAI — privacy, compatibility, use cases, and getting started.',
    icon: '/icons/faq.svg',
    default: { w: 720, h: 600 },
  },
  'how-it-works': {
    id: 'how-it-works',
    title: 'How PAI works',
    description: 'How PAI works: amnesic live USB, offline AI, hardened networking, and free software — explained.',
    icon: '/icons/how-it-works.svg',
    default: { w: 900, h: 640 },
    single: true,
  },
  files: {
    id: 'files',
    title: 'Files',
    description: 'Browse and manage files on your PAI USB drive with the built-in file manager.',
    icon: '/icons/files.svg',
    default: { w: 880, h: 600 },
  },
  notepad: {
    id: 'notepad',
    title: 'Notepad',
    description: 'A minimal text editor for jotting notes and editing files on your PAI desktop.',
    icon: '/icons/notepad.svg',
    default: { w: 720, h: 540 },
  },
  privacy: {
    id: 'privacy',
    title: 'Privacy',
    description: 'How pai.direct handles your data: no analytics, no cookies, no tracking — by design.',
    icon: '/icons/security.svg',
    default: { w: 900, h: 640 },
    single: true,
  },
  calculator: {
    id: 'calculator',
    title: 'Calculator',
    description: 'A standard calculator with basic arithmetic, parentheses, percent, and keyboard support.',
    icon: '/icons/calculator.svg',
    default: { w: 320, h: 480 },
    single: true,
  },
  text: {
    id: 'text',
    title: 'Text',
    description: 'A simple text editor with open/save, line numbers, word wrap, and find/replace.',
    icon: '/icons/text.svg',
    default: { w: 760, h: 560 },
  },
  time: {
    id: 'time',
    title: 'Time',
    description: 'Clock, timer, stopwatch, and alarms — with world time zones.',
    icon: '/icons/time.svg',
    default: { w: 640, h: 520 },
    single: true,
  },
  gallery: {
    id: 'gallery',
    title: 'Gallery',
    description: 'Browse images in a grid and lightbox. Drop local images to add them.',
    icon: '/icons/gallery.svg',
    default: { w: 900, h: 640 },
  },
  taskmanager: {
    id: 'taskmanager',
    title: 'Task Manager',
    description: 'Inspect open windows, simulated system metrics, and PAI services.',
    icon: '/icons/taskmanager.svg',
    default: { w: 820, h: 600 },
    single: true,
  },
  settings: {
    id: 'settings',
    title: 'Settings',
    description: 'Configure appearance, sound, privacy, shortcuts, and more on your PAI desktop.',
    icon: '/icons/settings.svg',
    default: { w: 820, h: 600 },
    single: true,
  },
  music: {
    id: 'music',
    title: 'Music',
    description: 'Local-only audio player with queue, visualizer, and keyboard controls. Drag in files — nothing leaves your device.',
    icon: '/icons/music.svg',
    ogImage: '/og/default.svg',
    default: { w: 520, h: 640 },
  },
  camera: {
    id: 'camera',
    title: 'Camera',
    description: 'Capture stills and record video from your webcam. Everything stays local — photos and clips download straight to your device.',
    icon: '/icons/camera.svg',
    ogImage: '/og/default.svg',
    default: { w: 720, h: 540 },
    single: true,
  },
  studio: {
    id: 'studio',
    title: 'Studio',
    description: 'A creative sketch canvas — draw, fill, layer, and export as PNG. Private by design, no cloud sync.',
    icon: '/icons/studio.svg',
    ogImage: '/og/default.svg',
    default: { w: 900, h: 640 },
  },
  backup: {
    id: 'backup',
    title: 'Backup',
    description: 'Export and restore your PAI desktop state as a local JSON file — no cloud, no account.',
    icon: '/icons/backup.svg',
    default: { w: 720, h: 600 },
    single: true,
  },
  companion: {
    id: 'companion',
    title: 'Companion',
    description: 'A friendly PAI mascot that answers questions about PAI and opens relevant apps — runs offline.',
    icon: '/icons/companion.svg',
    default: { w: 560, h: 640 },
    single: true,
  },
  welcome: {
    id: 'welcome',
    title: 'Welcome',
    description: 'A quick tour of the PAI desktop — dock, context menu, search, and windows.',
    icon: '/icons/welcome.svg',
    default: { w: 640, h: 540 },
    single: true,
  },
  shortcuts: {
    id: 'shortcuts',
    title: 'Shortcuts',
    description: 'Every keyboard shortcut in PAI, grouped by app and searchable.',
    icon: '/icons/shortcuts.svg',
    default: { w: 760, h: 600 },
    single: true,
  },
}

export function appUrl(id, params) {
  const base = `/apps/${id}`
  if (!params || Object.keys(params).length === 0) return base
  return `${base}?${new URLSearchParams(params).toString()}`
}
